### ISSUE TITLE
Bock settings resetted after server restart

### ISSUE THREAD

**Issue by Marlin994** [RLNT/minecraft_energymeter#18]
### Version

1.18.1-3.1.0

### Describe the bug!

Hey, I'm playing the Enigmatica 8 Modpack with this mod on a Server. After every server restart the config of a Energymeter block gets resettet. 

### Additional Context

Yes

### Modifications

Enigmatica 8 Modpack V1.0.5

### Did the issue happen in singleplayer or on a server?

Server

**Comment by rlnt** [comment]
Edit: Thank you for the report!

This is caused by a breaking change in Forge.
Reference: https://github.com/MinecraftForge/MinecraftForge/pull/8235

The fix will be uploaded shortly. Once the build is published, you should notify the Modpack maintainers about this change so they update to the newest version if that didn't already happen.
