### ISSUE TITLE
Transfert Rate Limit

### ISSUE THREAD

**Issue by Xen0Xys** [RLNT/minecraft_energymeter#24]
### Describe the feature/addition!

Like the original Energy Meters mod, allow the player to set a transfert rate limit to the energy meter.

### Why would like to see this feature/addition?

I want it because no other mod do that in 1.18.2, and because this feature is present in the original mod.

**Comment by rlnt** [comment]
This is not a direct port of the original mod. Since I assume you have played both versions, you have probably seen that there are fundamental differences. I only adapted the idea because the 1.12 mod was no longer maintained and I liked its functionality.

I don't see this feature as very fitting for the scope of a metering block because its only function should be to measure the flow rate. However, an energy limiter is a nice idea but it does not fit into this mod because of its name. That would be misleading in my opinion.

One of the core concepts I changed that differs from the original mod is the I/O system. The mod from 1.12 had one input port and one output port while Energy Meter has one input and multiple outputs where the energy is equally distributed to. Deciding if the transfer rate limit would apply to all outputs or per output is also not that easy.

Feel free to leave your opinion but I don't think it's a good feature for the Meter.
